### ISSUE TITLE
Thirst and Temperature placeholders

### ISSUE THREAD

**Issue by Playerbabudj2** [ValMobile/RealisticSurvival#25] opened 2023-02-15 16:54 UTC
### ❗ Checklist

- [X] I have checked that my requested feature does not exist on the most up-to-date "dev-build" (not "Spigot") version of Realistic Survival.
- [X] I know that feature requests related to other plugins need to be reported on their feature request trackers and not here.
- [X] I searched for similar feature requests and could not find an existing form on this.
- [X] I know that feature requests should align to Realistic Survival's goal of recreating the RLCraft modpack experience.
- [X] I understand that my requested feature may not be added due to time constraints or other limitations.

### 📍 What problem do you want to solve?

Make HappyHUD work with RealisticSurvival using placeholders

### 💡 What would you change, add, or modify to solve the problem?

Add placeholders for Thirst and Temperature

### 🌐 How do you see your suggestion benefiting the majority of servers?

Yes, placeholders could be used in a huge amount of ways, e.g. someone has to use scoreboard instead of actionbar, they want to use HappyHud etc etc.

### 🎮 Module

Tough as Nails

### 💰 Donations and Partnerships

- [ ] I fall into one of the categories listed above.

**Comment by ValMobile** [comment] 2023-02-16 21:51
Hi, I will start working on this suggestion once compatibility for other plugins is implemented.

**Comment by ValMobile** [comment] 2023-02-16 21:54
This is a duplicate of #20, so that suggestion is also considered accepted.

**Comment by ValMobile** [comment] 2023-06-11 03:47
Placeholders are added as of 1.2.5-RELEASE.

**Closed** 2023-06-12 22:48 UTC
Labels: 🗻 Suggestion
